#!/usr/bin/env bash
#
# Generate static/llms-full.txt from the four agent-facing documents.
#
# WHY THIS IS A SCRIPT AND NOT A HAND-EDITED FILE
#   llms-full.txt is the llmstxt.org "everything in one context window" file. Written
#   by hand it is a fifth copy of four documents, and it drifts the first time one of
#   them is edited. So it is generated, and `handlers::llms_full_txt_is_in_sync`
#   fails the build if the committed output no longer matches its sources.
#
# THE FORMAT IS PART OF THE CONTRACT
#   The Rust test rebuilds this exact string from the same four files. If you change
#   HEADER or the separator here, change it there too or the test goes red.
#
# Usage: ./scripts/build_llms_full.sh   (from anywhere; paths resolve off this file)
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

out="static/llms-full.txt"
sources=(static/llms.txt static/index.md static/skill.md static/auth.md)

for f in "${sources[@]}"; do
  [ -f "$f" ] || { echo "missing source: $f" >&2; exit 1; }
done

{
  printf '# x402 Payment Facilitator - Ultravioleta DAO - full agent context\n'
  printf '#\n'
  printf '# Generated by scripts/build_llms_full.sh. Do not edit by hand: edit the\n'
  printf '# sources below and re-run it. Sources, in order: %s\n' "${sources[*]}"
  printf '\n---\n\n'

  first=1
  for f in "${sources[@]}"; do
    if [ $first -eq 0 ]; then printf '\n---\n\n'; fi
    first=0
    # Strip CR so a checkout with CRLF endings produces the same bytes as one
    # with LF. The Rust sync test normalises the same way, for the same reason.
    tr -d '\r' < "$f"
  done
} > "$out"

echo "wrote $out ($(wc -c < "$out") bytes) from ${#sources[@]} sources"
