//! Canary for the OFAC list the facilitator ships, `config/ofac_addresses.json`.
//!
//! The list is a file, regenerated by `scripts/update_ofac_list.py` from the
//! SDN Advanced XML that OFAC publishes, and nothing else keeps it current:
//! from 2025-11-16 to 2026-09-29 it was never regenerated, and every
//! designation in between was missing from it. These tests read the SHIPPED
//! file through the same builder `main.rs` uses, so going back to a list that
//! predates a designation fails here instead of in production.

use std::path::PathBuf;

use x402_compliance::lists::ofac::LIST_NAME;
use x402_compliance::{
    ComplianceChecker, ComplianceCheckerBuilder, Config, ScreeningDecision, TransactionContext,
};

/// The digital currency addresses of the SDN entries created on 2026-05-20
/// (profiles 57107 and 57118, `Digital Currency Address - ETH`), spelled as
/// the SDN Advanced XML issued on 2026-09-29 spells them. None of them is in
/// the list generated on 2025-11-16.
const DESIGNATED_2026_05_20: [&str; 6] = [
    "0x038989cbb1710c72b9920dc4fa529158f463e72c",
    "0x14779CEC0B117d5194c750C55Ea1f42086631964",
    "0x32dA24Ca413F3E7B53145D4737e172C3bdF81e3e",
    "0xf2235d55b2950a0b1317469d72d07ae65b2e27cb",
    "0x4F428c11Dc82388fa5136D636e613ad923Eb700B",
    "0xaC4cC4B68ea24BbFAAC8fD127B67Ed445ACcCE22",
];

/// 2026-05-20T00:00:00Z: the list has to be at least this recent to hold them.
const DESIGNATION_DAY_UNIX: i64 = 1_779_235_200;

/// The positive control: the facilitator's own mainnet EVM signer, as
/// `lambda/balances/handler.py` records it. Well-formed, and on no list.
const CONTROL: &str = "0x103040545AC5031A11E8C03dd11324C7333a13C7";

/// The file the image copies to `/app/config`.
fn shipped_list() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../config/ofac_addresses.json")
}

/// A checker over the shipped OFAC list alone, built the way `main.rs` builds
/// its own. The custom blacklist is not what is under test.
async fn checker() -> Box<dyn ComplianceChecker> {
    let mut config = Config::default();
    config.lists.ofac.path = shipped_list();
    config.blacklist_path = None;
    let file = tempfile::NamedTempFile::new().unwrap();
    std::fs::write(file.path(), toml::to_string(&config).unwrap()).unwrap();
    ComplianceCheckerBuilder::new()
        .with_ofac(true)
        .with_config_file(file.path())
        .build()
        .await
        .expect("the shipped OFAC list loads")
}

fn context() -> TransactionContext {
    TransactionContext {
        amount: "1000000".to_string(),
        currency: "USDC".to_string(),
        network: "base".to_string(),
        transaction_id: None,
    }
}

#[tokio::test]
async fn the_2026_05_20_designation_is_blocked() {
    let checker = checker().await;
    for address in DESIGNATED_2026_05_20 {
        // As a recipient: what `/register` asks before it mints.
        let decision = checker.screen_address(address).await.unwrap();
        assert!(
            matches!(decision, ScreeningDecision::Block { .. }),
            "{address} (SDN, 2026-05-20) is not blocked: config/ofac_addresses.json \
             predates its designation; regenerate it with scripts/update_ofac_list.py"
        );
        // As the payer of a verify or a settle.
        let result = checker
            .screen_payment(address, CONTROL, &context())
            .await
            .unwrap();
        assert!(
            matches!(result.decision, ScreeningDecision::Block { .. }),
            "{address} (SDN, 2026-05-20) is not blocked as a payer"
        );
    }
}

/// Without this, a checker that blocked everything would pass the canary.
#[tokio::test]
async fn an_address_on_no_list_is_clear() {
    let checker = checker().await;
    assert!(
        matches!(
            checker.screen_address(CONTROL).await.unwrap(),
            ScreeningDecision::Clear
        ),
        "{CONTROL} is on no list and must screen clear"
    );
    let result = checker
        .screen_payment(CONTROL, CONTROL, &context())
        .await
        .unwrap();
    assert!(
        matches!(result.decision, ScreeningDecision::Clear),
        "{CONTROL} paying itself must screen clear"
    );
}

/// `/health/ready` tells the list's age from this date; a file without one
/// would read `degraded` there for good.
#[tokio::test]
async fn the_shipped_list_says_when_it_was_generated() {
    let metadata = checker().await.list_metadata();
    let ofac = metadata.get(LIST_NAME).expect("the OFAC list is loaded");
    let generated_at = ofac
        .generated_at
        .expect("config/ofac_addresses.json carries an RFC 3339 metadata.generated_at");
    assert!(
        generated_at.timestamp() >= DESIGNATION_DAY_UNIX,
        "generated {generated_at}, before the 2026-05-20 designation it must hold"
    );
}
